## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Spindelnet - Pentest"
copyright = "{year}"


theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"



## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Pentest"
  logo = "images/5.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/clysel/"
  twitter = "https://twitter.com/clysel"
  linkedin = "https://linkedin.com/in/clysel"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]

