## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Hugo Story"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

