## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

